#!/usr/bin/env python3
"""Housekeeping job 18 — shard `raw/` into `raw/YYYY/`, and rewrite every reference.

Two phases, run in order by default:

  1. MOVE   every entry in `raw/` into `raw/<YYYY>/`, where YYYY is the four-digit
            year prefix every filename already carries (`reference.md` §3). Artefacts
            (PDF, .txt sidecars, .csv, .docx) move with their own year prefix, which
            is always the year of their companion page — so a bare `artefact:` value
            keeps resolving as a sibling and needs no rewrite.

  2. REWRITE every explicit `raw/<name>` path in the repo to `raw/<YYYY>/<name>`.
            Matching is against the literal set of the 8,203 known filenames (and the
            `.md` stems, since many references drop the extension), longest match
            first. That is why a filename containing spaces, brackets or accents is
            handled exactly, and why prose like "withdraw/transfer" or a bare `raw/`
            can never be hit by accident — nothing matches unless it names a real file.

**Bare `[[wikilinks]]` are untouched and unaffected**: they resolve by filename across
the vault regardless of folder, and the 7,770 stems are unique by construction.

Line endings are preserved (`newline=""` on read and write) — the repo is mixed CRLF/LF
and a migration must not smuggle in an EOL change (`CLAUDE.md`, and the same discipline
as `entity-mint-apply.py`).

Usage:
  python scripts/shard-raw.py --dry-run      # report only, touch nothing
  python scripts/shard-raw.py --move         # phase 1 only
  python scripts/shard-raw.py --rewrite      # phase 2 only
  python scripts/shard-raw.py                # both
"""

import argparse
import collections
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "raw")

# Directories whose contents are never rewritten.
#   .git          — object store
#   .obsidian     — gitignored UI state; Obsidian rewrites its own recent-files list
#   __pycache__   — build artefacts
#   archived-procs— retired apparatus, kept as a historical record
#   outputs       — DERIVED; regenerated by the finance compile, not hand-maintained
SKIP_DIRS = {".git", ".obsidian", "__pycache__", "archived-procs", "outputs", "node_modules"}

# File types that carry references worth keeping live.
REWRITE_EXT = {".md", ".csv", ".py"}


def year_of(name):
    """The shard a file belongs in — its own four-digit filename prefix."""
    return name[:4]


def listing():
    """Current flat contents of raw/. Errors if the shard already exists."""
    entries = sorted(os.listdir(RAW))
    files, dirs = [], []
    for e in entries:
        (dirs if os.path.isdir(os.path.join(RAW, e)) else files).append(e)
    return files, dirs


def build_map(files):
    """filename -> YYYY, refusing anything without a plausible year prefix."""
    m, bad = {}, []
    for f in files:
        y = year_of(f)
        if not re.match(r"^(19|20)\d{2}$", y):
            bad.append(f)
            continue
        m[f] = y
    return m, bad


# ---------------------------------------------------------------- phase 1: move
def phase_move(m, dry):
    by_year = collections.Counter(m.values())
    print("=== phase 1 — move ===")
    for y in sorted(by_year):
        print("  raw/%s/  %5d files" % (y, by_year[y]))
    print("  total: %d files into %d year directories" % (len(m), len(by_year)))
    if dry:
        return
    for y in sorted(by_year):
        d = os.path.join(RAW, y)
        if not os.path.isdir(d):
            os.mkdir(d)
    moved = 0
    for f, y in sorted(m.items()):
        src = os.path.join(RAW, f)
        dst = os.path.join(RAW, y, f)
        if os.path.exists(dst):
            print("  !! destination exists, skipped: %s" % dst, file=sys.stderr)
            continue
        os.rename(src, dst)
        moved += 1
    print("  moved: %d" % moved)


# ------------------------------------------------------------- phase 2: rewrite
def build_pattern(m):
    """One alternation over every filename and every .md stem, longest first.

    Longest-first is what makes `raw/<stem>.pdf` bind to the full PDF name rather
    than to the `.md` stem that is its prefix.
    """
    keys = {}
    for f, y in m.items():
        keys[f] = y
        if f.endswith(".md"):
            keys[f[:-3]] = y
    alts = sorted(keys, key=len, reverse=True)
    # (?<!\w) so prose like "withdraw/transfer" cannot match, while the relative
    # forms `../raw/…` and `../../raw/…` — which is how most wiki pages and
    # `ingested_log.md` cite a source — still do.
    pat = re.compile(r"(?<!\w)raw/(" + "|".join(re.escape(k) for k in alts) + r")")
    return pat, keys


def phase_rewrite(m, dry):
    pat, keys = build_pattern(m)
    print("=== phase 2 — rewrite ===")

    targets = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            if os.path.splitext(fn)[1].lower() in REWRITE_EXT:
                targets.append(os.path.join(dirpath, fn))
    targets.append(os.path.join(ROOT, ".gitignore"))

    total, touched = 0, []
    for p in targets:
        if not os.path.exists(p):
            continue
        try:
            t = io.open(p, encoding="utf-8", newline="").read()
        except (UnicodeDecodeError, OSError):
            continue
        if "raw/" not in t:
            continue
        n = [0]

        def sub(mo):
            n[0] += 1
            return "raw/%s/%s" % (keys[mo.group(1)], mo.group(1))

        new = pat.sub(sub, t)
        if n[0]:
            total += n[0]
            rel = os.path.relpath(p, ROOT).replace("\\", "/")
            touched.append((n[0], rel))
            if not dry:
                io.open(p, "w", encoding="utf-8", newline="").write(new)

    touched.sort(reverse=True)
    print("  references rewritten: %d across %d files" % (total, len(touched)))
    for c, rel in touched[:25]:
        print("    %5d  %s" % (c, rel))
    if len(touched) > 25:
        print("    ... and %d more files" % (len(touched) - 25))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--move", action="store_true")
    ap.add_argument("--rewrite", action="store_true")
    a = ap.parse_args()
    do_move = a.move or not (a.move or a.rewrite)
    do_rw = a.rewrite or not (a.move or a.rewrite)

    files, dirs = listing()
    if dirs and do_move:
        print("raw/ already holds directories: %s" % ", ".join(dirs), file=sys.stderr)
        print("Refusing to move again. Use --rewrite alone.", file=sys.stderr)
        return 1
    if not files and do_move:
        print("raw/ holds no loose files — nothing to move.", file=sys.stderr)
        return 1

    # The reference map must describe the pre-move layout, so build it from the
    # flat listing when moving, and from the sharded tree when rewriting alone.
    if files:
        m, bad = build_map(files)
    else:
        m, bad = {}, []
        for y in dirs:
            for f in os.listdir(os.path.join(RAW, y)):
                m[f] = y
    if bad:
        print("  !! no year prefix, left in place: %d" % len(bad), file=sys.stderr)
        for f in bad:
            print("     %s" % f, file=sys.stderr)
        return 1

    if do_move:
        phase_move(m, a.dry_run)
    if do_rw:
        phase_rewrite(m, a.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
