#!/usr/bin/env python3
"""drop-digest.py — what ingest threw back from each sweep over the last rotation.

Strategic review 5 R72. The parent pastes this output verbatim at the top of the night's
sweep brief (`SWEEP-CYCLE.md` -> *What every sub-agent prompt carries*), so a sweep opens
knowing the three classes it misfired on last time. Generated, never written by hand.

It counts what the manifest's `drops` block counts (`cycle-manifest.py`, schema 3): ingest's
coded drops from `sweep/ingest/drop-log-*.csv` (INGEST.md step 11), keyed by the night in each
row's `sweep_batch` and grouped by sweep with the same `sweep_of()`. The manifest itself is
overwritten nightly and git-ignored, so it cannot be read back; the drop-logs it is counted
from can.

The rotation is the number of days in `logs/sweep-cycle_log.md`'s table, ending yesterday.

Usage:  python scripts/drop-digest.py [--today YYYY-MM-DD]
"""
import csv
import datetime
import glob
import importlib.util
import os
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("cycle_manifest", os.path.join(HERE, "cycle-manifest.py"))
CM = importlib.util.module_from_spec(spec)
spec.loader.exec_module(CM)


def main():
    argv = sys.argv[1:]
    today = datetime.date.today()
    if "--today" in argv:
        today = datetime.date.fromisoformat(argv[argv.index("--today") + 1])
    days = (CM.rotation() or {}).get("days") or 7
    last = today - datetime.timedelta(days=1)
    first = last - datetime.timedelta(days=days - 1)
    nights = {(first + datetime.timedelta(d)).isoformat() for d in range(days)}

    per = {}
    for path in glob.glob(os.path.join(CM.SWEEP_DIR, "ingest", "drop-log-*.csv")):
        try:
            with open(path, encoding="utf-8", errors="replace", newline="") as fh:
                for r in csv.DictReader(fh):
                    key, night = CM.sweep_of(r.get("sweep_batch"))
                    if night in nights:
                        d = per.setdefault(key or "no-batch", {})
                        code = r.get("reason") or "uncoded"
                        d[code] = d.get(code, 0) + 1
        except OSError:
            continue

    print(f"## What ingest threw back — last rotation, {first} to {last}")
    print()
    print("*(Generated by `scripts/drop-digest.py`, not written. Each line is items this sweep "
          "staged that ingest then deleted, by `intake.md` §7 code. If your sweep is listed, "
          "screen those classes out tonight — they are what a false pass costs.)*")
    print()
    if not per:
        print("- No coded ingest drops in this rotation yet.")
        return 0
    for key, codes in sorted(per.items(), key=lambda kv: -sum(kv[1].values())):
        top = sorted(codes.items(), key=lambda kv: (-kv[1], kv[0]))[:3]
        print(f"- **{key}** — " + " · ".join(f"`{c}` {n}" for c, n in top)
              + f" (of {sum(codes.values())} ingest drops)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
